slip_min: 1
slip_max: 0.5
max_range: 2
basic_sensor_variance: 0.5
max_range: 2.0
samples: 360
resolution: 1
min_angle: 0.0
max_angle: 6.28319
min: 0.12
max: 3.5
robot_noise_mean: 0.0
robot_noise_stddev: 0.01
