slip_min: 0.00
slip_max: 0.1
max_range: 2
basic_sensor_variance: 0.01
max_range: 0.5
samples: 360
resolution: 1
min_angle: 0.0
max_angle: 6.28319
scan_time: 1.0
min: 0.12
max: 3.5
laser_variance: 0.01
robot_noise_mean: 0.0
robot_noise_stddev: 0.1
